set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports C]
# set_property IOSTANDARD LVCMOS33 [get_ports baud_rate_clk]
set_property IOSTANDARD LVCMOS33 [get_ports clock_50]
# set_property IOSTANDARD LVCMOS33 [get_ports Coincidence_0]
# set_property IOSTANDARD LVCMOS33 [get_ports Coincidence_1]
# set_property IOSTANDARD LVCMOS33 [get_ports Coincidence_2]
# set_property IOSTANDARD LVCMOS33 [get_ports Coincidence_3]
set_property IOSTANDARD LVCMOS33 [get_ports D]
#set_property IOSTANDARD LVCMOS33 [get_ports data_trigger]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TXD]
set_property PACKAGE_PIN D14 [get_ports A]
set_property PACKAGE_PIN F16 [get_ports B]
set_property PACKAGE_PIN G16 [get_ports C]
set_property PACKAGE_PIN H14 [get_ports D]
set_property PACKAGE_PIN C17 [get_ports UART_TXD]
set_property PACKAGE_PIN E3 [get_ports clock_50]
